### PR TITLE
Reduce feedback to 5%

### PR DESCRIPTION
**Pull request by commuterjoy**
as per conversion /cc @matthew-andrews

### CODE REVIEW

**Comment by matthew-andrews** [comment]
umm…… i thought we decided to aggregate them……

**Comment by commuterjoy** [comment]
oooh, I thought we said the daily churn of opt-outs can be seen on beacon, so the individual emails don't add a lot of value. The ones marked 'other' do offer specific complaints/comments from readers, so I kept those. Happy to change if you think that's wrong?

**Comment by matthew-andrews** [comment]
can check with chris with what we think most useful……

perhaps i'm thinking it's easier than it actually is but something like every hour

> in the past hour:-
> 5 people opted out because of poor-visuals
> 2 people opted out because of difficult-navigation
> see individual opt outs here

**Comment by matthew-andrews** [comment]
[then handwritten messages as they are]

**Comment by commuterjoy** [comment]
yup, that makes sense.

**Pull request merged**
